# Generated by Django 5.0.2 on 2024-04-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_order_options_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Genre',
            field=models.TextField(blank=True, default='', verbose_name='Жанр'),
        ),
    ]
