# Generated by Django 5.0.2 on 2024-04-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_product_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Genre',
            new_name='genre',
        ),
        migrations.AddField(
            model_name='product',
            name='developer',
            field=models.TextField(blank=True, default='', verbose_name='Разработчик'),
        ),
        migrations.AddField(
            model_name='product',
            name='publisher',
            field=models.TextField(blank=True, default='', verbose_name='Издатель'),
        ),
        migrations.AddField(
            model_name='product',
            name='release',
            field=models.TextField(blank=True, default='', verbose_name='Дата выхода'),
        ),
    ]
