# Generated by Django 5.0.3 on 2024-04-10 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_product_categories_alter_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='genre',
        ),
    ]
